### ISSUE TITLE
conserved nucleotides are not shown in auspice

### ISSUE THREAD

**Issue by andersonbrito** [nextstrain/ncov#414] opened 2020-05-22 19:25 UTC
**Current Behavior**  

`auspice` doesn't show legend labels for conserved nucleotides when "Color by > Genotype > nucleotide" is selected. 

Examples:

- Site 106 has a C or a T at that position, and both are shown. All good!
https://nextstrain.org/ncov/global?c=gt-nuc_106

- But site 107 has only As (strictly conserved), but the Adenine label is not shown in the legend.
https://nextstrain.org/ncov/global?c=gt-nuc_107

**Expected behavior**  
Conserved nucleotide positions to be shown in the legend.

**How to reproduce**  
Click on the links posted above.

**Your environment: if browsing Nextstrain online**  
 - Operating system:  MacOS
 - Browser: Firefox, Safari and Chrome (same behavior in all browsers)

**Your environment: if running Nextstrain locally**  
 - Operating system:  MacOS
 - Browser: Firefox, Safari and Chrome (same behavior in all browsers)
 - Version: `auspice 2.10.0`  

**Additional context**  
The same issue is observed while visualizing the results on https://auspice-us.herokuapp.com/.

**Comment by emmahodcroft** [comment] 2020-05-22 20:29
Hi @andersonbrito ! You've spotted a really good issue. This is something we've been aware of for a while and we agree that what happens here is not ideal. 

However, at the moment this is the only action that's available because we do not actually export the entire sequence alignment (or any entire sequence) into the JSON that goes into Auspice - so we only have site information for variable sites!

We were (pre-pandemic) actively working on a way to implement some exporting features so that we would indeed know the state of even non-variables sites, as we agree this is really helpful! At the moment, we've not been able to push further on this due to everything SARS-CoV-2 related, but your issue is a good reminder that this is still on the table, unresolved! We'll be working on how to get this working soon, and hopefully we'll have this resolved in the not-too-distant future!

**Comment by andersonbrito** [comment] 2020-05-23 03:58
Hi @emmahodcroft, I can imagine how busy you all are at the moment. No rush, the intention was mostly to let you know, in case this was an unknown bug. Glad to know this issue report will be useful in some way. Cheers!

**Comment by jameshadfield** [comment] 2020-05-24 21:43
This is a timely reminder for us to implement this functionality in auspice. The issue is https://github.com/nextstrain/auspice/issues/616. 

I'm going to keep this issue open in case it's useful for other people, but this is an auspice thing, not an nCoV thing!

**Comment by rneher** [comment] 2020-12-10 09:02
this is implemented in auspice now.

**Closed by rneher** 2020-12-10 09:02 UTC
Labels: enhancement
