### ISSUE TITLE
ERROR: TREE BUILDING FAILED

### ISSUE THREAD

**Issue by jmtembo** [nextstrain/ncov#818] opened 2021-12-14 21:05 UTC
**Current Behavior**
I keep getting this error when trying to build a phylogenetic tree.
WARNING: more threads requested than there are sequences; falling back to IQ-TREE's `-nt AUTO` mode.

ERROR: Shell exited 2 when running: iqtree2 -ninit 2 -n 2 -me 0.05 -nt AUTO -s results/default-build/aligned-delim.fasta -m GTR -ninit 10 -n 4 > results/default-build/aligned-delim.iqtree.log
Command output was:
  OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
  ERROR: Cannot read file results/default-build/aligned-delim.fasta

Building a tree via:
	iqtree2 -ninit 2 -n 2 -me 0.05 -nt AUTO -s results/default-build/aligned-delim.fasta -m GTR -ninit 10 -n 4 > results/default-build/aligned-delim.iqtree.log
	Nguyen et al: IQ-TREE: A fast and effective stochastic algorithm for estimating maximum likelihood phylogenies.
	Mol. Biol. Evol., 32:268-274. https://doi.org/10.1093/molbev/msu300

ERROR: TREE BUILDING FAILED
Please see the log file for more details: results/default-build/aligned-delim.iqtree.log

Building original tree took 0.09787392616271973 seconds
Waiting at most 5 seconds for missing files.
MissingOutputException in line 1158 of /Users/johntembo/ncov-9/workflow/snakemake_rules/main_workflow.smk:
Job Missing files after 5 seconds:
results/default-build/tree_raw.nwk
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 6 completed successfully, but some output files are missing. 6
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/johntembo/ncov-9/.snakemake/log/2021-12-14T222627.178962.snakemake.log

**Possible solution**
(optional)

**Your environment: if browsing Nextstrain online**
 - Operating system: macOs
 - Browser:

**Your environment: if running Nextstrain locally**
 - Operating system:MACOS
 - Browser:
 - Version (e.g. `auspice 2.7.0`):

**Additional context**

**Comment by huddlej** [comment] 2021-12-23 18:35
Hi @jmtembo! This warning message suggests that there very few sequences in your input alignment.

> WARNING: more threads requested than there are sequences

When this happens, IQ-TREE doesn't have enough data to build a tree and will crash. Can you check your alignment FASTA file (`results/default-build/aligned.fasta`) to confirm how many sequences there are? If there are fewer than you expect, you'll want to look upstream in the workflow a bit to see if an earlier filtering step has removed sequences than you intended to keep. You can force include specific sequences by adding their strain names to the `defaults/include.txt` file or you can modify [the filter settings of the workflow](https://docs.nextstrain.org/projects/ncov/en/latest/reference/configuration.html#filter).

I'm going to close this issue for now, since it is likely to be a data-dependent issue, but if you find that the issue is with the ncov workflow itself, please reopen this and share any additional details you've collected.

**Closed by huddlej** 2021-12-23 18:35 UTC
Labels: bug
