### ISSUE TITLE
[BUG] Stop agreeing with the stupid Gisaid policy and simply share the database anywhere on the internet

### ISSUE THREAD

**Issue by acx01b** [nextstrain/ncov#394] opened 2020-05-06 07:07 UTC
And stop saying the labs asked their data to be shared through Gisaid,

you know very well that they just didn't understand people wouldn't have access to the dataset

**Comment by rvosa** [comment] 2020-05-08 12:11
I'm sure many people share this general sentiment but it is simply not an option for nextstrain (worst case scenario: their access to GISAID data is revoked). As far as feedback is concerned this issue is not at all constructive, and it is also not a bug. The logical response of the core developers would be to close this as there is nothing they can do in response.

**Comment by emmahodcroft** [comment] 2020-05-08 12:18
Thanks @rvosa . 
@acx01b , we are very aware that this is something that's frustrating to a lot of people, and I know there are a lot of strong feelings about it.

However, as Rutger says, we have agreed to follow the GISAID terms & conditions, and we must do so. This means we cannot share the metadata.tsv file anymore on Github. However, you can find instructions for how to access the same file (plus a sequences file) through the GISAID website [here](https://github.com/nextstrain/ncov/blob/master/docs/running.md#obtaining-global-data-through-gisaid).

As suggested by Rutger, I'm going to close the issue, but do know that we understand the high feelings around this. I hope the access through GISAID can still be helpful for you.

**Closed by emmahodcroft** 2020-05-08 12:18 UTC
Labels: bug
