### ISSUE TITLE
data download for "all-time" Europe is empty

### ISSUE THREAD

**Issue by eltrompetero** [nextstrain/ncov#989] opened 2022-08-09 11:59 UTC
**Current Behavior**
I tried downloading the phylo tree data but am getting an empty file. I get a file with data if I select a different time period, 6m or 2m.

**Expected behavior**
I tried downloading the phylo tree data but am getting an empty file. Expected behavior fulfilled with other time periods and "global" region.

**How to reproduce**
Steps to reproduce the current behavior:
1. Select europe as as region.
2. Select "all-time".
3. Download data.

No other settings were changed. Empty file with both "time" and "divergence" trees.

**Your environment: if browsing Nextstrain online**
 - Operating system: Mac OS
 - Browser: Safari

Thanks!

**Comment by emmahodcroft** [comment] 2022-08-09 12:11
I'm afraid wasn't able to replicate this on `open` or `gisaid` on Windows 10, Chrome, Edge, or Firefox. It might be a Mac or Safari-specific problem? 
Someone else from Nextstrain might be on a Mac and able to test in those cases. 

Just to confirm, are you trying to download the `gisaid` tree - and are you choosing the "Timetree (Newick)" option, or another?

**Comment by eltrompetero** [comment] 2022-08-09 12:30
Thanks so much for the rapid response.

You're right, it seems to be a browser specific issue. It didn't seem like it should be one since the download was working for other settings...but it is!

The settings were just as you said. I didn't change anything else besides the options I specified.

**Comment by emmahodcroft** [comment] 2022-08-09 12:43
Hi @eltrompetero - it's good to hear that you got it working! I guess it was Safari that didn't work, but another browser did? 

It would still be useful for us to look into this if we can, since it could be affecting others. In particular, as you say - it working then not working either after a specific sequence or on a specific dataset, is particularly odd.

**Comment by eltrompetero** [comment] 2022-08-09 12:45
Apologies, I didn't specify. Firefox v103 worked for me. Safari did not work.

**Comment by eltrompetero** [comment] 2022-08-09 12:55
Possibly related: when I try the same settings as before but specify all clades except for Delta and Omicron, I also receive an empty file.

Maybe these are both query errors? E.g. the query is very long in this particular example.

**Comment by joverlee521** [comment] 2022-08-09 18:29
Hmm, I am able to download the Newick tree even when using Safari on MacOS 10.14.6 from https://nextstrain.org/ncov/gisaid/europe/all-time. 

> Possibly related: when I try the same settings as before but specify all clades except for Delta and Omicron, I also receive an empty file.

This is a separate [known issue in Auspice](https://github.com/nextstrain/auspice/issues/1267) that filtered data produces empty trees unless you use the [workaround](https://github.com/nextstrain/auspice/issues/1267#issuecomment-767846905) in the linked issue.

**Comment by victorlin** [comment] 2022-08-09 21:49
Also unable to reproduce. I've tried Safari, Microsoft Edge, and Google Chrome. All on latest versions and on macOS 12.3.1.

**Comment by eltrompetero** [comment] 2022-08-11 08:04
I'm confirming now that the all-time Europe download, which was the start of the thread, works fine on Safari. Very strange.

I still had the same problem with selecting all clades except for Delta and Omicron returning an empty file, but using "zoom selected" solved my problem as mentioned above.

Thanks for all the suggestions.

**Comment by joverlee521** [comment] 2022-08-11 22:15
Closing this issue since we are unable to reproduce. Please let us know if you run in to any other issues!

**Closed by joverlee521** 2022-08-11 22:15 UTC
Labels: bug
