### ISSUE TITLE
Discrepancy in clade assignment between Nextclade and Augur

### ISSUE THREAD

**Issue by crl9k** [nextstrain/ncov#856] opened 2022-02-04 18:48 UTC
**Current Behavior**
21K/L (Nextclade) is assigned to 21M and even 20A by Augur (today's build...).

**Expected behavior**
No discrepancy in clade assignment between Nextclade and Augur.

**How to reproduce**
snakemake --profile my_profiles/local -p (using a local install of Nextstrain environment/ncov workflow)

**Your environment: if running Nextstrain locally**
 - Operating system: CentOS 7
 - Browser: Firefox 96
 - Version (e.g. `auspice 2.7.0`): nextclade 1.10.2, augur 13.1.1

What am I missing?

Thank you for your help.

**Comment by emmahodcroft** [comment] 2022-02-06 14:21
Hi @crl9k - I assume you mean a particular sequence is being assigned differently between the builds? Unfortunately this can happen sometimes. Nextclade is usually the most reliable way to assign sequences to a clade, as this operates with a specially-constructed, standardized tree and QC metrics. Within the live Nextstrain build, these are "live" builds - we make them fresh every day, and sometimes if we pick an odd handful of sequences (we pick a new sampling every day) we might end up with an odd assignment or two due to real-time tree building, which then sets the clades on the tree in the most appropriate places.

However, this should only happen occasionally. If you're seeing this happen to specific sequences repeatedly, please do post an example and we can look into it in more depth.

**Comment by emmahodcroft** [comment] 2022-02-07 18:44
Hi @crl9k  - Hm, that's interesting. My guess is that there's something going on with where they end up on the tree - for Nextstrain this can be influenced by what else is in the tree - are these assignments you're seeing in the Nextstrain builds (https://nextstrain.org/ncov/gisaid/global for example), or in a local build?

Are you able to share any of the sequences, and point out where they are falling in the relevant Nextstrain build?

You can 'tune' the clade assignments by adjusting them in https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv - but you'll want to be careful, as this could lead to wrong assignments in Nextstrain.

**Comment by crl9k** [comment] 2022-02-08 15:30
Hi @emmahodcroft - the assignments are in a local build of more than 2000 sequences.
You will find attached 20 21K (Nextclade) sequences: 10 assigned to 20A and 10 assigned to 21M by Augur.

Thank you for your help.
[seq.zip](https://github.com/nextstrain/ncov/files/8025156/seq.zip)

**Comment by emmahodcroft** [comment] 2022-02-08 16:15
Hi @crl9k - thanks for passing these on! 

For the 20A ones, I think I see what's going on - most of these (all except 1 I think) have 3 key reversions: 
![image](https://user-images.githubusercontent.com/14290674/153026152-0fa7fb2a-5626-45f7-bf7d-278cdf8c522f.png)
These sites are really key sites for defining the 20B branch, which is what Omicron splits off from:
https://nextstrain.org/ncov/gisaid/global?c=gt-nuc_28881,28882,28883

I'm guessing that since you have these reversions, in the tree it is using these to place these sequences in 20A rather than Omicron. It's still a bit surprising, since the rest of the mutations are clearly Omicron, but depending on the other sequences in your tree, and the background, it could be really weighing on the 28881,28882,28883, which is a very significant split in the tree, and this may be throwing things off.

Alternatively, if you have quite a small tree with only a few sequences, the `ncov` workflow also defines all of the Omicron labels (21K, 21M, 21L) [by these mutations](https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv#L118) - so if there isn't many other sequences to determine the structure/label placement, it may well put the label on the other side of these sequences, because of their lack of these mutations.

The 21M file is less clear what's going on. I am wondering if perhaps whatever's messing up the calling of the other sequences, might be impacting where the 21K label falls. Are you able to give any more information about the tree this is happening in?

**Comment by crl9k** [comment] 2022-02-08 16:31
Attached is the tree I get.

Thank you for your help.
![tree](https://user-images.githubusercontent.com/12101220/153031645-c4d4c83a-ed9b-45fc-ba1f-129497000b33.png)

**Comment by emmahodcroft** [comment] 2022-02-10 10:09
Hi @crl9k - thanks for sending a snap of the tree! Yes, it looks like the tree is probably having trouble resolving the early splits in the tree (and thus things like where 20A and 20B begin) because it doesn't have many early samples to work with. For example, since a few of your Omicron samples are missing those key mutations to define 20B, and it has no other sequences that have these mutations, this will be really throwing these off. 

If possible, I'd try to sprinkle through some earlier sequences, from the first half of 2020 - maybe a hundred or so? This should help the tree reconstruct the early structure better, including putting 20A/20B etc in the right place. This should then help assign correct labels further down the Omicron branch. 
I hope that helps!

**Comment by emmahodcroft** [comment] 2022-02-14 10:02
Hi @crl9k - I'm sorry to hear that adding more 20A/20B sequence didn't resolve the issue - that's surprising, I had thought this might do the trick. I think the problem is a combination of where the tree is thinking the 28881/28882 mutation arose, and having those mutations revert in some of the 21K sequences -- but it's clearly a little more complex than just trying to get this mutation in the right place on the tree with added 20A/20B sequences.

I'm much less sure what's going on with the 21L/21M sequences, as when I ran them through Nextclade I found the same - they seem to be clearly 21L. My guess is that the deeper structural issues that are impacting how 20A/21K are probably impacting the calling here, though it's less apparent how. 

Unfortunately I'm not sure we have very good documentation on how the clades file works in practice, and I'm not sure we have plans for another publication soon. I'm looking into whether we can add more clear description of how the clades work in our documentation!

**Comment by corneliusroemer** [comment] 2022-02-14 10:56
@crl9k could you share the auspice.json of your tree? That way it's easiest to see why augur clades behaves the way it does.

There's a reason clades are placed as they are, it's almost definitely due to tree topology and not a bug in ncov per se. Happy to have a quick look but without the auspice.json I don't think I can do much.

**Comment by corneliusroemer** [comment] 2022-02-14 18:28
@crl9k kindly sent the auspice.json to Emma and me via email. I'll close this issue, if there are any actionable results, we'll post here, or maybe transfer to discussion.nextstrain.org

**Closed by corneliusroemer** 2022-02-14 18:28 UTC
Labels: question

**Comment by crl9k** [comment] 2022-05-24 10:08
For the record and for others having this issue, I ended up using the "reference data" maintained by the Nextstrain team that represent all Nextstrain clades annotated for SARS-CoV-2 (cf. https://data.nextstrain.org/files/ncov/open/reference/[metadata.tsv.xz|sequences.fasta.xz], https://docs.nextstrain.org/projects/ncov/en/latest/tutorial/example-data.html). Mixing this reference data with my data, I do not need anymore to tweak the clades.tsv file. However, my 21L sequences keep assigned to 21M by augur. But they all miss the 21618T mutation.

Of note: I maintain builds iteratively and to keep the reference data up to date, I had to modify ncov/workflow/snakemake_rules/common.smk file, removing "keep_local=True" when calling path_or_url function in _get_path_for_input line 121.

Of note 2: Do we have to adapt the filter settings to include all the reference sequences? When running the pipeline only on the reference data, I noticed in the logs that some strains "were dropped because they were in results/default-build/excluded_by_diagnostics.txt" or "because of 'division=USA'".

And I had an overview of how the clade assignment works going through the augur/augur/clades.py file, especially the assign_clades function (cf. https://github.com/nextstrain/augur/blob/master/augur/clades.py).

Thank you.
