### ISSUE TITLE
Logistic growth is broken on example build

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/ncov#623] opened 2021-05-04 03:42 UTC
**Current Behavior**
Logistic grown, when run on the default example build only produces valid data for a small number of nodes, with most being assigned `NaN` like so:
```json
{
  "generated_by": {
    "program": "augur",
    "version": "12.0.0"
  },
  "nodes": {
    "Australia/VIC05/2020": {
      "current_frequency": 0.0,
      "logistic_growth": NaN
    },
    "Australia/VIC1008/2020": {
      "current_frequency": 0.0,
      "logistic_growth": NaN
    },
```

Presumably this is due to not enough data, or a divide-by-zero thing? cc @huddlej 

![image](https://user-images.githubusercontent.com/8350992/116958604-4e8da900-acef-11eb-98e3-7dfdb1a39cbc.png)

**How to reproduce**
Steps to reproduce the current behavior:
1. `snakemake  -p --profile my_profiles/example -f auspice/ncov_global.json`

**Your environment: if running Nextstrain locally**
 - augur 12.0.0

**Comment by huddlej** [comment] 2021-05-05 17:50
This is a "not enough data" issue. [The default parameters for logistic growth](https://github.com/nextstrain/ncov/blob/7a71f49c76de7d269930ff431b4853abd8378dca/defaults/parameters.yaml#L101-L114) were tuned for larger trees and require at least 50 tips in a clade and strict min/max frequency thresholds.

We could change these parameters in the `builds.yaml` for the example build, but the results won't be that much more meaningful with so little data.

**Comment by huddlej** [comment] 2021-12-23 18:42
Closing this since the issue is related to the unavoidably small data set and the fact that logistic growth calculations intentionally don't assign values to sparse clades in trees like the one shown above.

**Closed by huddlej** 2021-12-23 18:42 UTC
Labels: bug
