### ISSUE TITLE
Error while run clades using the same data

### ISSUE THREAD

**Issue by hhy18** [nextstrain/ncov#436] opened 2020-06-15 12:51 UTC
Question:

The two sequences are  identical, but when using a script for CLade it is found that the two data are assigned to different clade (19A, 20B)?

Description:
the sequence id Australia/NSW54/2020 and Australia/NSW152/2020 are identical (the same), but the result  run with assign_clades.py are assigned into different clade(19A, 20B). Can someone tell me why the same sequence doesn't assign the same clade?

Thanks

**Comment by rneher** [comment] 2020-06-15 14:19
Thanks for filing the issue. But I can't reproduce this. both  Australia/NSW54/2020 and Australia/NSW152/2020 are assigned to 20B when I run the script.  Australia/NSW52/2020, however, is indeed 19A. If this issue persists, please let us know the exact set of input sequences to that we can try to reproduce this.

**Comment by hhy18** [comment] 2020-06-16 08:02
Thank you very much for your reply. In my result, Australia/NSW152/2020 assigned to 19A and Australia/NSW54/2020  20B are assigned to  20B. My cmd is  that python assign_clades.py --sequences sequences_cov2.fasta --chunk-size 100  --nthreads 100.  
I've run it a couple of times, and it's always like this and I don't know why. 
Here are my output files. 
[clade_assignment.zip](https://github.com/nextstrain/ncov/files/4783976/clade_assignment.zip)

**Comment by hhy18** [comment] 2020-06-16 15:33
Thank you very much for your reply. In my result, Australia/NSW152/2020(EPI_ISL_427648) assigned to 19A and Australia/NSW54/2020 (EPI_ISL_417407) are assigned to 20B. But we found the two sequences are the same, I don't why assigned to different claded.&nbsp;
My cmd is that python assign_clades.py --sequences sequences_cov2.fasta --chunk-size 100 --nthreads 100. I've run it a couple of times, and it's always like this and I don't know why.
Here are my input and&nbsp; output files.




------------------ 原始邮件 ------------------
发件人:&nbsp;"Richard Neher"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 晚上10:20
收件人:&nbsp;"nextstrain/ncov"<ncov@noreply.github.com&gt;;
抄送:&nbsp;"铁打的星星"<1036720428@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nextstrain/ncov] Error while run clades using the same data (#436)





 
Thanks for filing the issue. But I can't reproduce this. both  Australia/NSW54/2020 and Australia/NSW152/2020 are assigned to 20B when I run the script.  Australia/NSW52/2020, however, is indeed 19A. If this issue persists, please let us know the exact set of input sequences to that we can try to reproduce this.

**Comment by hhy18** [comment] 2020-06-17 01:43
Thank you very much for your reply. In my result, Australia/NSW152/2020(EPI_ISL_427648) assigned to 19A and Australia/NSW54/2020 (EPI_ISL_417407) are assigned to 20B. But we found the two sequences are the same, I don't why assigned to different claded;

My cmd is that python assign_clades.py --sequences sequences_cov2.fasta --chunk-size 100 --nthreads 100. I've run it a couple of times, and it's always like this and I don't know why.

Here are my input and output files.
[clade_assignment.zip](https://github.com/nextstrain/ncov/files/4789885/clade_assignment.zip)
[test.zip](https://github.com/nextstrain/ncov/files/4789886/test.zip)

**Comment by rneher** [comment] 2020-06-17 16:09
hi @hhy18, thanks again. Turns out there was a problem with how the script was handling insertions relative to the reference. I have modified it to use augurs align command and now it should work. I tested it on your sequences and got the expected result.

**Comment by rneher** [comment] 2020-06-26 17:56
I think is fixed -- please reopen if not.

**Closed by rneher** 2020-06-26 17:56 UTC
Labels: bug
